### ISSUE TITLE
"main" in package.json and bower.json no longer point to valid file

### ISSUE THREAD

**Issue by ixtli** [components/rsvp.js#7]
https://github.com/components/rsvp.js/blob/master/bower.json#L9
https://github.com/components/rsvp.js/blob/master/package.json#L6

I have scripted some build tools that rely on these fields. and since bower uses this repo why you do `bower install rsvp` my CI setup is now unhappy. I will submit a pr if they simply need to be changed to remove the `dist/` part.

**Comment by ixtli** [comment]
Upon further investigation is seems like this may be a regression. This commit ( https://github.com/components/rsvp.js/commit/0b1e4942dd638d6b49ae8a8e7a3b35f1efbbdce7 ) fixes the issue but then this commit ( https://github.com/components/rsvp.js/commit/b0d560c894de0895050f8f2072c4cd8a04f9dfec ) reintroduces the old path.

**Comment by martinlindhe** [comment]
Agree, seems to be a regression. Care to brew up a patch?

**Comment by stefanpenner** [comment]
https://github.com/components/rsvp.js/tree/3.0.21
